version: 0.2
phases:
  install:
    commands:
      - |
        export DEBIAN_FRONTEND=noninteractive
        #Install php8.1
        apt-get update
        apt-get install -y  software-properties-common
        LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php
        apt-get update
        # Install PHP
        apt-get install -y php8.1\
                 php8.1-ldap \
                 php8.1-xml \
                 php8.1-xmlrpc \
                 php8.1-zip \
                 php8.1-mysql \
                 php8.1-mbstring \
                 php8.1-mcrypt \
                 php8.1-gd \
                 php8.1-readline \
                 php8.1-opcache \
                 php8.1-xdebug \
                 php8.1-dom \
                 php-xdebug \
                 php8.1-curl \
                 unzip
        #Enable xdebug - phpunit uses this for code coverage
        phpenmod xdebug
        #Install composer
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php ;
        php -r "unlink('composer-setup.php');" ;
        mv composer.phar /usr/local/bin/composer
  build:
    commands:
      - echo Build started on `date`
      - echo Installing composer deps
      - composer install --no-progress --no-suggest
      - echo Compiling the application
  post_build:
    commands:
      - echo Build completed on `date`
      - php artisan optimize:clear
      - cp .env.example .env
      - ./vendor/bin/phpunit
artifacts:
  files:
    - '**/*'
  name: development-deploy-build.zip
proxy:
  upload-artifacts: yes
  logs: yes
